const products = [
    {
        id: 0,
        name: 'Hand bag',
        price: 29.67,
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum, aperiam!',
        instock: 5,
        imgSrc: 'bag1.jpg',
    },
    {
        id: 1,
        name: 'Trench coat',
        price: 29.67,
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum, aperiam!',
        instock: 5,
        imgSrc: 'f1.jpg',
    },
    {
        id: 2,
        name: 'Hand bag',
        price: 29.67,
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum, aperiam!',
        instock: 5,
        imgSrc: 'f3.jpg',
    },
    {
        id: 3,
        name: 'Hood',
        price: 29.67,
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum, aperiam!',
        instock: 5,
        imgSrc: 'f4.jpg',
    },
    {
        id: 4,
        name: 'Footwear',
        price: 29.67,
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum, aperiam!',
        instock: 5,
        imgSrc: 'foot2.jpg',
    },
    {
        id: 5,
        name: 'Footwear',
        price: 29.67,
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum, aperiam!',
        instock: 5,
        imgSrc: 'foot3.jpg',
    },
    {
        id: 6,
        name: 'Footwear',
        price: 29.67,
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum, aperiam!',
        instock: 5,
        imgSrc: 'foot4.jpg',
    },
    {
        id: 7,
        name: 'Footwear',
        price: 29.67,
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum, aperiam!',
        instock: 5,
        imgSrc: 'foot5.png',
    },
    {
        id: 8,
        name: 'Jacket',
        price: 29.67,
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum, aperiam!',
        instock: 5,
        imgSrc: 'jacket.jpg',
    },
    {
        id: 9,
        name: 'Footwear',
        price: 29.67,
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum, aperiam!',
        instock: 5,
        imgSrc: 'foot6.png',
    },
    {
        id: 10,
        name: 'Footwear',
        price: 29.67,
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum, aperiam!',
        instock: 5,
        imgSrc: 'footwear.jpg',
    },
    {
        id: 11,

        name: 'Wrist watch',
        price: 29.67,
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum, aperiam!',
        instock: 5,
        imgSrc: 'watch.jpg',
    },
];